### ISSUE TITLE
option.go uses outdated method signature from blank package

### ISSUE THREAD

**Issue by sprak3000** [Henry-Sarabia/apicalypse#15]
Found this while opening a [PR against the igdb library](https://github.com/Henry-Sarabia/igdb/pull/57). The build for the PR listed the following error when trying to grab the dependencies:

```
# github.com/Henry-Sarabia/apicalypse
../apicalypse/option.go:53:7: undefined: blank.RemoveSpace
../apicalypse/option.go:74:7: undefined: blank.RemoveSpace
```

Digging into it, the `blank` library updated to rename `RemoveSpace` to just `Remove` a few months ago.

**Comment by Henry-Sarabia** [comment]
Thanks for the fix @sprak3000!
